import {Button} from "std-widgets.slint";

export struct CalendarItem {
    visible: bool,
    week_num: int,
    
    day: int,
    month: int,
    year: int,
}

export struct CalendarWeek {
    week_data: [CalendarItem]
}

export component CalendarComponent inherits Rectangle {
    in property <CalendarItem> item: { week_num: 1, day: 1, visible: true };
    // Visible of rectangle
    visible: item.visible;
    // Border
    border-radius: 10px;
    border-width: 1px;
    border-color: grey;
    // Label with day info
    Text {
        text: item.day;
        visible: item.visible;
    }
}

export global CalendarLogic {
    pure callback get_current_date() -> CalendarItem;
    // update_month_data get: year, month
    pure callback get_month_data(int, int) -> [CalendarWeek];
}

export component Calendar inherits Rectangle {
    in-out property <bool> use_short_names: true;
    in-out property <int> count_weeks: 5;

    in-out property <length> col_space: 5px;
    in-out property <length> row_space: 5px;

    in-out property <CalendarItem> displayed;
    in-out property <CalendarItem> selected_item;
    property <[CalendarWeek]> month_data_demo: [
        { week_data: [{ day: 1 }, { day: 2 }, { day: 3 }, { day: 4 }, { day: 5 }, { day: 6 }, { day: 7 }] },
        { week_data: [{ day: 1 }, { day: 2 }, { day: 3 }, { day: 4 }, { day: 5 }, { day: 6 }, { day: 7 }] },
        { week_data: [{ day: 1 }, { day: 2 }, { day: 3 }, { day: 4 }, { day: 5 }, { day: 6 }, { day: 7 }] },
        { week_data: [{ day: 1 }, { day: 2 }, { day: 3 }, { day: 4 }, { day: 5 }, { day: 6 }, { day: 7 }] },
        { week_data: [{ day: 1 }, { day: 2 }, { day: 3 }, { day: 4 }, { day: 5 }, { day: 6 }, { day: 7 }] }
    ];

    in-out property <[CalendarWeek]> month_data;

    // DOW - Days of week;
    // TODO: Check how made this readonly.
    property <[{full: string, short: string}]> label_dow: [
        { full: "Monday", short: "Mon" },
        { full: "Tuesday", short: "Tue" },
        { full: "Wednesday", short: "Wed" },
        { full: "Thursday", short: "Thu" },
        { full: "Friday", short: "Fri" },
        { full: "Saturday", short: "Sat" },
        { full: "Sunday", short: "Sun" }
    ];

    VerticalLayout {
    
        // Button space
        HorizontalLayout {
            Button {
                clicked => {
                    debug("Selected data: ", displayed);
                    debug("Month data: ", month_data[0].week_data[0]);
                }
            }

            Text {
                text: "Year:" + displayed.year;
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            Button { }
        }

        // Main calendar
        VerticalLayout {
            spacing: col_space;
            for week in month_data: HorizontalLayout {
                // width: 50% * root.width;
                property <length> cell_width: self.width / 7;
                for day in week.week_data: CalendarComponent {
                    item: { day: day.day, visible: day.visible };
                    width: cell_width;
                    height: cell_width;
                }
            }
        }
    }
}
