import { Calendar, CalendarItem, CalendarWeek  } from "@widgets/calendar.slint";
import { ClientInfo,ClientInfoSlint } from "@pages/client_info.slint";
import { IClientInfoLogic, ICalendarLogic} from "@logic/logic.slint";
export { ICalendarLogic, IClientInfoLogic }


export component MainWindow inherits Window {
    width: 548px;
    height: 600px;
    in-out property <int> test;

    // calendar := Calendar { }
    // in-out property client_id <=> IClientInfoLogic.current_client_id;
    // in-out property client <=> IClientInfoLogic.current_client;
    // pure callback get_user_info <=> IClientInfoLogic.get_user_info;
    ClientInfo { }
}
