// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "Client", 1, 4232924590366596268);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2118396169943376223);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 2420429962535564379);
    obx_model_property(model, "last_name", OBXPropertyType_String, 3, 9060221825843465878);
    obx_model_property(model, "additional_info", OBXPropertyType_String, 4, 5478106197915482444);
    obx_model_property(model, "diagnosis", OBXPropertyType_String, 5, 1835775022643446179);
    obx_model_property(model, "birthday_date", OBXPropertyType_Date, 6, 3200790165446494807);
    obx_model_entity_last_property_id(model, 7, 6437078930246871991);
    
    obx_model_entity(model, "EventStatus", 2, 178701048376682576);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3743004761803902039);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 1269261941935221798);
    obx_model_entity_last_property_id(model, 2, 1269261941935221798);
    
    obx_model_entity(model, "Events", 3, 2764412866232652727);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4914901320129076539);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "event_stat_id", OBXPropertyType_Relation, 2, 3080437405275653789);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "EventStatus", 1, 4835662900399819860);
    obx_model_property(model, "payment_stat_id", OBXPropertyType_Relation, 3, 3042416171413486389);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "PaymentStatus", 2, 6234586313957568125);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 2974585387743269004);
    obx_model_property(model, "start_date", OBXPropertyType_Date, 5, 4156345417899504069);
    obx_model_property(model, "end_date", OBXPropertyType_Date, 6, 6174844177528786463);
    obx_model_property(model, "duration", OBXPropertyType_Long, 7, 706082463420064439);
    obx_model_entity_last_property_id(model, 7, 706082463420064439);
    
    obx_model_entity(model, "PaymentStatus", 4, 7128285385869012364);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8962486209677227357);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 1868611908526886811);
    obx_model_entity_last_property_id(model, 2, 1868611908526886811);
    
    obx_model_entity(model, "Event", 5, 2275087930255141894);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4202322800725384350);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 6174680980825670351);
    obx_model_property(model, "description", OBXPropertyType_String, 3, 2685668261718824971);
    obx_model_property(model, "is_work_event", OBXPropertyType_Bool, 4, 7332813401351768790);
    obx_model_property(model, "event_stat_id", OBXPropertyType_Relation, 5, 6756516191170196090);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "EventStatus", 3, 8539627464916298022);
    obx_model_property(model, "payment_stat_id", OBXPropertyType_Relation, 6, 156741055834734281);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "PaymentStatus", 4, 6077000883603522273);
    obx_model_property(model, "start_date", OBXPropertyType_Date, 7, 8620128003167801451);
    obx_model_property(model, "end_date", OBXPropertyType_Date, 8, 5610333834680675135);
    obx_model_property(model, "duration", OBXPropertyType_Long, 9, 5716146653668202541);
    obx_model_entity_last_property_id(model, 9, 5716146653668202541);
    
    obx_model_entity(model, "ObxClient", 6, 1276055315771980492);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 452053588053143873);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 3808716636712114465);
    obx_model_property(model, "last_name", OBXPropertyType_String, 3, 2246920303058462103);
    obx_model_property(model, "additional_info", OBXPropertyType_String, 4, 3291871443426391515);
    obx_model_property(model, "diagnosis", OBXPropertyType_String, 5, 5823697886380435786);
    obx_model_property(model, "birthday_date", OBXPropertyType_Date, 6, 1489414232755749908);
    obx_model_entity_last_property_id(model, 6, 1489414232755749908);
    
    obx_model_entity(model, "ObxEvent", 7, 6312465015457351717);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2722298619602178402);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 1805498599114546254);
    obx_model_property(model, "description", OBXPropertyType_String, 3, 2923464261013182613);
    obx_model_property(model, "is_work_event", OBXPropertyType_Bool, 4, 4751643885648285417);
    obx_model_property(model, "event_stat_id", OBXPropertyType_Relation, 5, 1279799933926145338);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "EventStatus", 5, 710846959809792147);
    obx_model_property(model, "payment_stat_id", OBXPropertyType_Relation, 6, 4404538472672181582);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "PaymentStatus", 6, 5732402837582512403);
    obx_model_property(model, "start_date", OBXPropertyType_Date, 7, 1097158213809587039);
    obx_model_property(model, "end_date", OBXPropertyType_Date, 8, 8963752415450789323);
    obx_model_property(model, "duration", OBXPropertyType_Long, 9, 7949770622388427310);
    obx_model_entity_last_property_id(model, 9, 7949770622388427310);
    
    obx_model_entity(model, "ObxEventStatus", 8, 428495872392820867);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1945110493359752364);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 7863958216247807796);
    obx_model_entity_last_property_id(model, 2, 7863958216247807796);
    
    obx_model_entity(model, "ObxPaymentStatus", 9, 3913365336717971459);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2022963127944036031);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 840463892669945937);
    obx_model_entity_last_property_id(model, 2, 840463892669945937);
    
    obx_model_last_entity_id(model, 9, 3913365336717971459);
    obx_model_last_index_id(model, 6, 5732402837582512403);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
