// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "ObxClient", 1, 9222488863877849404);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4437955445005046920);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 3042717258127856013);
    obx_model_property(model, "last_name", OBXPropertyType_String, 3, 4930106246710698986);
    obx_model_property(model, "additional_info", OBXPropertyType_String, 4, 1032589761500929099);
    obx_model_property(model, "diagnosis", OBXPropertyType_String, 5, 4653121431483938636);
    obx_model_property(model, "birthday_date", OBXPropertyType_Date, 6, 7650197688374967512);
    obx_model_property(model, "email", OBXPropertyType_String, 7, 1130666697636446956);
    obx_model_property(model, "phone_number", OBXPropertyType_String, 8, 8026992687549155118);
    obx_model_property(model, "client_active", OBXPropertyType_Bool, 9, 4999055469204569816);
    obx_model_property(model, "country", OBXPropertyType_String, 10, 5581960358917280040);
    obx_model_property(model, "city", OBXPropertyType_String, 11, 8006821059546166440);
    obx_model_property(model, "time_zone", OBXPropertyType_String, 12, 5660384026665908964);
    obx_model_entity_last_property_id(model, 12, 5660384026665908964);
    
    obx_model_entity(model, "ObxEvent", 2, 6602257003920660585);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1863236555416346146);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 4154493402714280900);
    obx_model_property(model, "description", OBXPropertyType_String, 3, 8647926316662035098);
    obx_model_property(model, "is_work_event", OBXPropertyType_Bool, 4, 5337740726563963484);
    obx_model_property(model, "event_stat_id", OBXPropertyType_Relation, 5, 4788778188756128348);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxEventStatus", 1, 943550472254333744);
    obx_model_property(model, "payment_stat_id", OBXPropertyType_Relation, 6, 5927558126686696451);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxPaymentStatus", 2, 5525901426439236628);
    obx_model_property(model, "start_date", OBXPropertyType_Date, 7, 8167175638137048872);
    obx_model_property(model, "end_date", OBXPropertyType_Date, 8, 814619399907758219);
    obx_model_property(model, "duration", OBXPropertyType_Long, 9, 2489937869615063357);
    obx_model_entity_last_property_id(model, 9, 2489937869615063357);
    
    obx_model_entity(model, "ObxEventClient", 3, 8105372197119122755);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1505496827744851731);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "client_id", OBXPropertyType_Relation, 2, 7801791581035965306);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxClient", 3, 384473963347765670);
    obx_model_property(model, "event_id", OBXPropertyType_Relation, 3, 2760004704272577736);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxEvent", 4, 7673689708577955306);
    obx_model_entity_last_property_id(model, 3, 2760004704272577736);
    
    obx_model_entity(model, "ObxEventStatus", 4, 7474041764443288441);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1908433294440041011);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 1641681440468857588);
    obx_model_entity_last_property_id(model, 2, 1641681440468857588);
    
    obx_model_entity(model, "ObxPaymentStatus", 5, 3636246469301265828);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6223551215575050957);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 1212835695634219967);
    obx_model_entity_last_property_id(model, 2, 1212835695634219967);
    
    obx_model_last_entity_id(model, 5, 3636246469301265828);
    obx_model_last_index_id(model, 4, 7673689708577955306);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
