// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "Client", 1, 3468521987803626616);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1790679519265224047);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "full_name", OBXPropertyType_String, 2, 1834366785167723635);
    obx_model_property(model, "additional_info", OBXPropertyType_String, 3, 5339940091679734866);
    obx_model_property(model, "diagnosis", OBXPropertyType_String, 4, 3385632752934828738);
    obx_model_property(model, "birthday_date", OBXPropertyType_Date, 5, 7344132765916830536);
    obx_model_property(model, "age", OBXPropertyType_Int, 6, 8023984134330051196);
    obx_model_entity_last_property_id(model, 6, 8023984134330051196);
    
    obx_model_entity(model, "EventStatus", 2, 1528752484958038216);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 703642202298429365);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 1771188334721838481);
    obx_model_entity_last_property_id(model, 2, 1771188334721838481);
    
    obx_model_entity(model, "Events", 3, 5617031195646798220);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2231682210231775940);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "event_stat_id", OBXPropertyType_Relation, 2, 966502212980722938);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "EventStatus", 1, 9143853469194821369);
    obx_model_property(model, "payment_stat_id", OBXPropertyType_Relation, 3, 7993219737988037306);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "PaymentStatus", 2, 7862524356960001388);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 2512418019838792398);
    obx_model_property(model, "start_date", OBXPropertyType_Date, 5, 2794995860751103996);
    obx_model_property(model, "end_date", OBXPropertyType_Date, 6, 4468308897966105856);
    obx_model_property(model, "duration", OBXPropertyType_Long, 7, 3097153108871809618);
    obx_model_entity_last_property_id(model, 7, 3097153108871809618);
    
    obx_model_entity(model, "PaymentStatus", 4, 8836732327389694623);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 669587545881935907);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "name", OBXPropertyType_String, 2, 538677520308685345);
    obx_model_entity_last_property_id(model, 2, 538677520308685345);
    
    obx_model_last_entity_id(model, 4, 8836732327389694623);
    obx_model_last_index_id(model, 2, 7862524356960001388);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
