// Code generated by ObjectBox; DO NOT EDIT.

#include "scheme.obx.hpp"

const obx::Property<Client, OBXPropertyType_Long> Client_::id(1);
const obx::Property<Client, OBXPropertyType_String> Client_::name(2);
const obx::Property<Client, OBXPropertyType_String> Client_::last_name(3);
const obx::Property<Client, OBXPropertyType_String> Client_::additional_info(4);
const obx::Property<Client, OBXPropertyType_String> Client_::diagnosis(5);
const obx::Property<Client, OBXPropertyType_Date> Client_::birthday_date(6);

void Client::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Client& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetlast_name = fbb.CreateString(object.last_name);
    auto offsetadditional_info = fbb.CreateString(object.additional_info);
    auto offsetdiagnosis = fbb.CreateString(object.diagnosis);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    fbb.AddOffset(8, offsetlast_name);
    fbb.AddOffset(10, offsetadditional_info);
    fbb.AddOffset(12, offsetdiagnosis);
    fbb.AddElement(14, object.birthday_date);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Client Client::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Client object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Client> Client::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Client>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Client::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Client& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.last_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.last_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.additional_info.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.additional_info.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.diagnosis.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.diagnosis.clear();
        }
    }
    outObject.birthday_date = table->GetField<int64_t>(14, 0);
}

const obx::Property<EventStatus, OBXPropertyType_Long> EventStatus_::id(1);
const obx::Property<EventStatus, OBXPropertyType_String> EventStatus_::name(2);

void EventStatus::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const EventStatus& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

EventStatus EventStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    EventStatus object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<EventStatus> EventStatus::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<EventStatus>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void EventStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, EventStatus& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
}

const obx::Property<PaymentStatus, OBXPropertyType_Long> PaymentStatus_::id(1);
const obx::Property<PaymentStatus, OBXPropertyType_String> PaymentStatus_::name(2);

void PaymentStatus::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const PaymentStatus& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

PaymentStatus PaymentStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    PaymentStatus object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<PaymentStatus> PaymentStatus::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<PaymentStatus>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void PaymentStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, PaymentStatus& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
}

const obx::Property<Event, OBXPropertyType_Long> Event_::id(1);
const obx::Property<Event, OBXPropertyType_String> Event_::name(2);
const obx::Property<Event, OBXPropertyType_String> Event_::description(3);
const obx::Property<Event, OBXPropertyType_Bool> Event_::is_work_event(4);
const obx::RelationProperty<Event, EventStatus> Event_::event_stat_id(5);
const obx::RelationProperty<Event, PaymentStatus> Event_::payment_stat_id(6);
const obx::Property<Event, OBXPropertyType_Date> Event_::start_date(7);
const obx::Property<Event, OBXPropertyType_Date> Event_::end_date(8);
const obx::Property<Event, OBXPropertyType_Long> Event_::duration(9);

void Event::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Event& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetdescription = fbb.CreateString(object.description);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    fbb.AddOffset(8, offsetdescription);
    fbb.AddElement(10, object.is_work_event ? 1 : 0);
    fbb.AddElement(12, object.event_stat_id);
    fbb.AddElement(14, object.payment_stat_id);
    fbb.AddElement(16, object.start_date);
    fbb.AddElement(18, object.end_date);
    fbb.AddElement(20, object.duration);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Event Event::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Event object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Event> Event::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Event>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Event::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Event& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.description.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.description.clear();
        }
    }
    outObject.is_work_event = table->GetField<uint8_t>(10, 0) != 0;
    outObject.event_stat_id = table->GetField<obx_id>(12, 0);
    outObject.payment_stat_id = table->GetField<obx_id>(14, 0);
    outObject.start_date = table->GetField<int64_t>(16, 0);
    outObject.end_date = table->GetField<int64_t>(18, 0);
    outObject.duration = table->GetField<int64_t>(20, 0);
}

