// Code generated by ObjectBox; DO NOT EDIT.

#include "scheme.obx.hpp"

const obx::Property<Client, OBXPropertyType_Long> Client_::id(1);
const obx::Property<Client, OBXPropertyType_String> Client_::full_name(2);
const obx::Property<Client, OBXPropertyType_String> Client_::additional_info(3);
const obx::Property<Client, OBXPropertyType_String> Client_::diagnosis(4);
const obx::Property<Client, OBXPropertyType_Date> Client_::birthday_date(5);
const obx::Property<Client, OBXPropertyType_Int> Client_::age(6);

void Client::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Client& object) {
    fbb.Clear();
    auto offsetfull_name = fbb.CreateString(object.full_name);
    auto offsetadditional_info = fbb.CreateString(object.additional_info);
    auto offsetdiagnosis = fbb.CreateString(object.diagnosis);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetfull_name);
    fbb.AddOffset(8, offsetadditional_info);
    fbb.AddOffset(10, offsetdiagnosis);
    fbb.AddElement(12, object.birthday_date);
    fbb.AddElement(14, object.age);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Client Client::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Client object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Client> Client::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Client>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Client::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Client& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.full_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.full_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.additional_info.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.additional_info.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.diagnosis.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.diagnosis.clear();
        }
    }
    outObject.birthday_date = table->GetField<int64_t>(12, 0);
    outObject.age = table->GetField<int32_t>(14, 0);
}

const obx::Property<EventStatus, OBXPropertyType_Long> EventStatus_::id(1);
const obx::Property<EventStatus, OBXPropertyType_String> EventStatus_::name(2);

void EventStatus::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const EventStatus& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

EventStatus EventStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    EventStatus object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<EventStatus> EventStatus::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<EventStatus>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void EventStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, EventStatus& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
}

const obx::Property<Events, OBXPropertyType_Long> Events_::id(1);
const obx::RelationProperty<Events, EventStatus> Events_::event_stat_id(2);
const obx::RelationProperty<Events, PaymentStatus> Events_::payment_stat_id(3);
const obx::Property<Events, OBXPropertyType_String> Events_::description(4);
const obx::Property<Events, OBXPropertyType_Date> Events_::start_date(5);
const obx::Property<Events, OBXPropertyType_Date> Events_::end_date(6);
const obx::Property<Events, OBXPropertyType_Long> Events_::duration(7);

void Events::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Events& object) {
    fbb.Clear();
    auto offsetdescription = fbb.CreateString(object.description);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.event_stat_id);
    fbb.AddElement(8, object.payment_stat_id);
    fbb.AddOffset(10, offsetdescription);
    fbb.AddElement(12, object.start_date);
    fbb.AddElement(14, object.end_date);
    fbb.AddElement(16, object.duration);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Events Events::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Events object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Events> Events::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Events>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Events::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Events& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.event_stat_id = table->GetField<obx_id>(6, 0);
    outObject.payment_stat_id = table->GetField<obx_id>(8, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.description.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.description.clear();
        }
    }
    outObject.start_date = table->GetField<int64_t>(12, 0);
    outObject.end_date = table->GetField<int64_t>(14, 0);
    outObject.duration = table->GetField<int64_t>(16, 0);
}

const obx::Property<PaymentStatus, OBXPropertyType_Long> PaymentStatus_::id(1);
const obx::Property<PaymentStatus, OBXPropertyType_String> PaymentStatus_::name(2);

void PaymentStatus::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const PaymentStatus& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

PaymentStatus PaymentStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    PaymentStatus object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<PaymentStatus> PaymentStatus::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<PaymentStatus>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void PaymentStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, PaymentStatus& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
}

