// Code generated by ObjectBox; DO NOT EDIT.

#include "scheme.obx.hpp"

const obx::Property<ObxClient, OBXPropertyType_Long> ObxClient_::id(1);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::name(2);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::last_name(3);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::additional_info(4);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::diagnosis(5);
const obx::Property<ObxClient, OBXPropertyType_Date> ObxClient_::birthday_date(6);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::email(7);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::phone_number(8);
const obx::Property<ObxClient, OBXPropertyType_Bool> ObxClient_::client_active(9);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::country(10);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::city(11);
const obx::Property<ObxClient, OBXPropertyType_String> ObxClient_::time_zone(12);

void ObxClient::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxClient& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetlast_name = fbb.CreateString(object.last_name);
    auto offsetadditional_info = fbb.CreateString(object.additional_info);
    auto offsetdiagnosis = fbb.CreateString(object.diagnosis);
    auto offsetemail = fbb.CreateString(object.email);
    auto offsetphone_number = fbb.CreateString(object.phone_number);
    auto offsetcountry = fbb.CreateString(object.country);
    auto offsetcity = fbb.CreateString(object.city);
    auto offsettime_zone = fbb.CreateString(object.time_zone);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    fbb.AddOffset(8, offsetlast_name);
    fbb.AddOffset(10, offsetadditional_info);
    fbb.AddOffset(12, offsetdiagnosis);
    fbb.AddElement(14, object.birthday_date);
    fbb.AddOffset(16, offsetemail);
    fbb.AddOffset(18, offsetphone_number);
    fbb.AddElement(20, object.client_active ? 1 : 0);
    fbb.AddOffset(22, offsetcountry);
    fbb.AddOffset(24, offsetcity);
    fbb.AddOffset(26, offsettime_zone);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ObxClient ObxClient::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ObxClient object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ObxClient> ObxClient::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ObxClient>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ObxClient::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ObxClient& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.last_name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.last_name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.additional_info.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.additional_info.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(12);
        if (ptr) {
            outObject.diagnosis.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.diagnosis.clear();
        }
    }
    outObject.birthday_date = table->GetField<int64_t>(14, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(16);
        if (ptr) {
            outObject.email.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.email.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(18);
        if (ptr) {
            outObject.phone_number.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.phone_number.clear();
        }
    }
    outObject.client_active = table->GetField<uint8_t>(20, 0) != 0;
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(22);
        if (ptr) {
            outObject.country.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.country.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(24);
        if (ptr) {
            outObject.city.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.city.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(26);
        if (ptr) {
            outObject.time_zone.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.time_zone.clear();
        }
    }
}

const obx::Property<ObxEvent, OBXPropertyType_Long> ObxEvent_::id(1);
const obx::Property<ObxEvent, OBXPropertyType_String> ObxEvent_::name(2);
const obx::Property<ObxEvent, OBXPropertyType_String> ObxEvent_::description(3);
const obx::Property<ObxEvent, OBXPropertyType_Bool> ObxEvent_::is_work_event(4);
const obx::RelationProperty<ObxEvent, ObxEventStatus> ObxEvent_::event_stat_id(5);
const obx::RelationProperty<ObxEvent, ObxPaymentStatus> ObxEvent_::payment_stat_id(6);
const obx::Property<ObxEvent, OBXPropertyType_Date> ObxEvent_::start_date(7);
const obx::Property<ObxEvent, OBXPropertyType_Date> ObxEvent_::end_date(8);
const obx::Property<ObxEvent, OBXPropertyType_Long> ObxEvent_::duration(9);

void ObxEvent::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxEvent& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    auto offsetdescription = fbb.CreateString(object.description);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    fbb.AddOffset(8, offsetdescription);
    fbb.AddElement(10, object.is_work_event ? 1 : 0);
    fbb.AddElement(12, object.event_stat_id);
    fbb.AddElement(14, object.payment_stat_id);
    fbb.AddElement(16, object.start_date);
    fbb.AddElement(18, object.end_date);
    fbb.AddElement(20, object.duration);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ObxEvent ObxEvent::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ObxEvent object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ObxEvent> ObxEvent::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ObxEvent>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ObxEvent::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ObxEvent& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.description.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.description.clear();
        }
    }
    outObject.is_work_event = table->GetField<uint8_t>(10, 0) != 0;
    outObject.event_stat_id = table->GetField<obx_id>(12, 0);
    outObject.payment_stat_id = table->GetField<obx_id>(14, 0);
    outObject.start_date = table->GetField<int64_t>(16, 0);
    outObject.end_date = table->GetField<int64_t>(18, 0);
    outObject.duration = table->GetField<int64_t>(20, 0);
}

const obx::Property<ObxEventClient, OBXPropertyType_Long> ObxEventClient_::id(1);
const obx::RelationProperty<ObxEventClient, ObxClient> ObxEventClient_::client_id(2);
const obx::RelationProperty<ObxEventClient, ObxEvent> ObxEventClient_::event_id(3);

void ObxEventClient::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxEventClient& object) {
    fbb.Clear();
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.client_id);
    fbb.AddElement(8, object.event_id);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ObxEventClient ObxEventClient::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ObxEventClient object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ObxEventClient> ObxEventClient::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ObxEventClient>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ObxEventClient::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ObxEventClient& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.client_id = table->GetField<obx_id>(6, 0);
    outObject.event_id = table->GetField<obx_id>(8, 0);
}

const obx::Property<ObxEventStatus, OBXPropertyType_Long> ObxEventStatus_::id(1);
const obx::Property<ObxEventStatus, OBXPropertyType_String> ObxEventStatus_::name(2);

void ObxEventStatus::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxEventStatus& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ObxEventStatus ObxEventStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ObxEventStatus object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ObxEventStatus> ObxEventStatus::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ObxEventStatus>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ObxEventStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ObxEventStatus& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
}

const obx::Property<ObxPaymentStatus, OBXPropertyType_Long> ObxPaymentStatus_::id(1);
const obx::Property<ObxPaymentStatus, OBXPropertyType_String> ObxPaymentStatus_::name(2);

void ObxPaymentStatus::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxPaymentStatus& object) {
    fbb.Clear();
    auto offsetname = fbb.CreateString(object.name);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetname);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ObxPaymentStatus ObxPaymentStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ObxPaymentStatus object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ObxPaymentStatus> ObxPaymentStatus::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ObxPaymentStatus>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ObxPaymentStatus::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ObxPaymentStatus& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.name.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.name.clear();
        }
    }
}

