// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


struct Client_;

struct Client {
    obx_id id;
    std::string name;
    std::string last_name;
    std::string additional_info;
    std::string diagnosis;
    int64_t birthday_date;
    int32_t age;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(Client& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Client& object);
    
        /// Read an object from a valid FlatBuffer
        static Client fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Client> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Client& outObject);
    };
};

struct Client_ {
    static const obx::Property<Client, OBXPropertyType_Long> id;
    static const obx::Property<Client, OBXPropertyType_String> name;
    static const obx::Property<Client, OBXPropertyType_String> last_name;
    static const obx::Property<Client, OBXPropertyType_String> additional_info;
    static const obx::Property<Client, OBXPropertyType_String> diagnosis;
    static const obx::Property<Client, OBXPropertyType_Date> birthday_date;
    static const obx::Property<Client, OBXPropertyType_Int> age;
};


struct EventStatus_;

struct EventStatus {
    obx_id id;
    std::string name;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 2; }
    
        static void setObjectId(EventStatus& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const EventStatus& object);
    
        /// Read an object from a valid FlatBuffer
        static EventStatus fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<EventStatus> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, EventStatus& outObject);
    };
};

struct EventStatus_ {
    static const obx::Property<EventStatus, OBXPropertyType_Long> id;
    static const obx::Property<EventStatus, OBXPropertyType_String> name;
};

struct EventStatus; 
struct PaymentStatus; 

struct Events_;

struct Events {
    obx_id id;
    obx_id event_stat_id;
    obx_id payment_stat_id;
    std::string description;
    int64_t start_date;
    int64_t end_date;
    int64_t duration;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 3; }
    
        static void setObjectId(Events& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Events& object);
    
        /// Read an object from a valid FlatBuffer
        static Events fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Events> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Events& outObject);
    };
};

struct Events_ {
    static const obx::Property<Events, OBXPropertyType_Long> id;
    static const obx::RelationProperty<Events, EventStatus> event_stat_id;
    static const obx::RelationProperty<Events, PaymentStatus> payment_stat_id;
    static const obx::Property<Events, OBXPropertyType_String> description;
    static const obx::Property<Events, OBXPropertyType_Date> start_date;
    static const obx::Property<Events, OBXPropertyType_Date> end_date;
    static const obx::Property<Events, OBXPropertyType_Long> duration;
};


struct PaymentStatus_;

struct PaymentStatus {
    obx_id id;
    std::string name;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 4; }
    
        static void setObjectId(PaymentStatus& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const PaymentStatus& object);
    
        /// Read an object from a valid FlatBuffer
        static PaymentStatus fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<PaymentStatus> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, PaymentStatus& outObject);
    };
};

struct PaymentStatus_ {
    static const obx::Property<PaymentStatus, OBXPropertyType_Long> id;
    static const obx::Property<PaymentStatus, OBXPropertyType_String> name;
};

