// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


struct ObxClient_;

struct ObxClient {
    obx_id id;
    std::string name;
    std::string last_name;
    std::string additional_info;
    std::string diagnosis;
    int64_t birthday_date;
    std::string email;
    std::string phone_number;
    bool client_active;
    std::string country;
    std::string city;
    std::string time_zone;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(ObxClient& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxClient& object);
    
        /// Read an object from a valid FlatBuffer
        static ObxClient fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<ObxClient> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, ObxClient& outObject);
    };
};

struct ObxClient_ {
    static const obx::Property<ObxClient, OBXPropertyType_Long> id;
    static const obx::Property<ObxClient, OBXPropertyType_String> name;
    static const obx::Property<ObxClient, OBXPropertyType_String> last_name;
    static const obx::Property<ObxClient, OBXPropertyType_String> additional_info;
    static const obx::Property<ObxClient, OBXPropertyType_String> diagnosis;
    static const obx::Property<ObxClient, OBXPropertyType_Date> birthday_date;
    static const obx::Property<ObxClient, OBXPropertyType_String> email;
    static const obx::Property<ObxClient, OBXPropertyType_String> phone_number;
    static const obx::Property<ObxClient, OBXPropertyType_Bool> client_active;
    static const obx::Property<ObxClient, OBXPropertyType_String> country;
    static const obx::Property<ObxClient, OBXPropertyType_String> city;
    static const obx::Property<ObxClient, OBXPropertyType_String> time_zone;
};

struct ObxEventStatus; 
struct ObxPaymentStatus; 

struct ObxEvent_;

struct ObxEvent {
    obx_id id;
    std::string name;
    std::string description;
    bool is_work_event;
    obx_id event_stat_id;
    obx_id payment_stat_id;
    int64_t start_date;
    int64_t end_date;
    int64_t duration;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 2; }
    
        static void setObjectId(ObxEvent& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxEvent& object);
    
        /// Read an object from a valid FlatBuffer
        static ObxEvent fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<ObxEvent> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, ObxEvent& outObject);
    };
};

struct ObxEvent_ {
    static const obx::Property<ObxEvent, OBXPropertyType_Long> id;
    static const obx::Property<ObxEvent, OBXPropertyType_String> name;
    static const obx::Property<ObxEvent, OBXPropertyType_String> description;
    static const obx::Property<ObxEvent, OBXPropertyType_Bool> is_work_event;
    static const obx::RelationProperty<ObxEvent, ObxEventStatus> event_stat_id;
    static const obx::RelationProperty<ObxEvent, ObxPaymentStatus> payment_stat_id;
    static const obx::Property<ObxEvent, OBXPropertyType_Date> start_date;
    static const obx::Property<ObxEvent, OBXPropertyType_Date> end_date;
    static const obx::Property<ObxEvent, OBXPropertyType_Long> duration;
};

struct ObxClient; 
struct ObxEvent; 

struct ObxEventClient_;

struct ObxEventClient {
    obx_id id;
    obx_id client_id;
    obx_id event_id;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 3; }
    
        static void setObjectId(ObxEventClient& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxEventClient& object);
    
        /// Read an object from a valid FlatBuffer
        static ObxEventClient fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<ObxEventClient> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, ObxEventClient& outObject);
    };
};

struct ObxEventClient_ {
    static const obx::Property<ObxEventClient, OBXPropertyType_Long> id;
    static const obx::RelationProperty<ObxEventClient, ObxClient> client_id;
    static const obx::RelationProperty<ObxEventClient, ObxEvent> event_id;
};


struct ObxEventStatus_;

struct ObxEventStatus {
    obx_id id;
    std::string name;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 4; }
    
        static void setObjectId(ObxEventStatus& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxEventStatus& object);
    
        /// Read an object from a valid FlatBuffer
        static ObxEventStatus fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<ObxEventStatus> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, ObxEventStatus& outObject);
    };
};

struct ObxEventStatus_ {
    static const obx::Property<ObxEventStatus, OBXPropertyType_Long> id;
    static const obx::Property<ObxEventStatus, OBXPropertyType_String> name;
};


struct ObxPaymentStatus_;

struct ObxPaymentStatus {
    obx_id id;
    std::string name;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 5; }
    
        static void setObjectId(ObxPaymentStatus& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ObxPaymentStatus& object);
    
        /// Read an object from a valid FlatBuffer
        static ObxPaymentStatus fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<ObxPaymentStatus> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, ObxPaymentStatus& outObject);
    };
};

struct ObxPaymentStatus_ {
    static const obx::Property<ObxPaymentStatus, OBXPropertyType_Long> id;
    static const obx::Property<ObxPaymentStatus, OBXPropertyType_String> name;
};

